name: nginx-deployment
on: push
jobs:
  my-job:
    runs-on: Windows
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Build Image
        shell: cmd
        run: docker build -t nagendrakilari/demo-git-repo . 
      - name: Push Image
        shell: cmd
        run: docker push nagendrakilari/demo-git-repo
